### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by j2l** [LPK99/AI-Storyboard-Stable-Diffusion-#1]
Great idea!
On spaces, I'm getting the error: `RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`
Do you also get this?

**Comment by MikeLuu99** [comment]
Yeah I am still trying to fix this problem on spaces. This error is likely because of running the repo on CPU instead of GPU on 
Huggingface spaces

But you should try to run this repo locally first, it seems to be running fine locally

**Comment by j2l** [comment]
ok, would you please let me know when it works?

**Comment by j2l** [comment]
Second thought, did you try on colab? Google provides a free GPU

**Comment by MikeLuu99** [comment]
Yeah, I am trying to host the streamlit app on Google Colab instead of just running locally.

**Comment by j2l** [comment]
Great! 
I have to learn how to adapt a local python project to run on colab, your commit will greatly help me!
Would you please let me know when it works?

**Comment by MikeLuu99** [comment]
Here is the Google Colab link https://colab.research.google.com/drive/1F94yAsoKDlrgVnTqJ6bAEhowqvqUsI97?usp=sharing

**Comment by j2l** [comment]
Great! Thank you very much!
Closing

**Comment by j2l** [comment]
Works very fine, even director's shortcuts like ECU for "Extreme Close Up" work!
```
Scene 1: [Long shot of a city near the sea]

Scene 2: [ECU of the main character's eye]
```

**Comment by j2l** [comment]
I think , a consistant style is needed, like this:
![image](https://github.com/LPK99/AI-Storyboard-Stable-Diffusion-/assets/65325/a9e54fe0-244f-480c-aa31-2a89fd9c8daf)

What do you think?
Do you see a way to achieve this?

**Comment by MikeLuu99** [comment]
For a more consistent style, you'll may need to finet-une the Stable
Diffusion model with images in a certain style or use a Lora model.
Be specific on the prompt would also somewhat improve the consistency of
the Storyboard.

**Comment by j2l** [comment]
Great idea!
Any idea how to add LORA model in this colab?

**Comment by MikeLuu99** [comment]
You can check out this Gitub repo
https://github.com/haofanwang/Lora-for-Diffusers
